# Generated by Django 4.1.7 on 2023-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kashy_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, default=2, max_length=50),
            preserve_default=False,
        ),
    ]
