# Generated by Django 4.1.7 on 2023-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kashy_database', '0003_student_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='kenya', max_length=50),
        ),
    ]
